/*
 * events_prints.h
 *
 *  Created on: Apr. 8, 2024
 *      Author: miyablon
 */

#ifndef EVENTS_PRINTS_H_
#define EVENTS_PRINTS_H_

#include "em_core.h"

const char * getString(long long unsigned int inputValue);

//#define RAIL_EVENTS_NONE 0ULL
#define RAIL_EVENT_RSSI_AVERAGE_DONE_TEXT ("RAIL_EVENT_RSSI_AVERAGE_DONE")
#define RAIL_EVENT_RX_ACK_TIMEOUT_TEXT ("RAIL_EVENT_RX_ACK_TIMEOUT")
#define RAIL_EVENT_RX_FIFO_ALMOST_FULL_TEXT ("RAIL_EVENT_RX_FIFO_ALMOST_FULL")
#define RAIL_EVENT_RX_PACKET_RECEIVED_TEXT ("RAIL_EVENT_RX_PACKET_RECEIVED")
#define RAIL_EVENT_RX_PREAMBLE_LOST_TEXT ("RAIL_EVENT_RX_PREAMBLE_LOST")
#define RAIL_EVENT_RX_PREAMBLE_DETECT_TEXT ("RAIL_EVENT_RX_PREAMBLE_DETECT")
#define RAIL_EVENT_RX_SYNC1_DETECT_TEXT ("RAIL_EVENT_RX_SYNC1_DETECT")
#define RAIL_EVENT_RX_SYNC2_DETECT_TEXT ("RAIL_EVENT_RX_SYNC2_DETECT")
#define RAIL_EVENT_RX_FRAME_ERROR_TEXT ("RAIL_EVENT_RX_FRAME_ERROR")
#define RAIL_EVENT_RX_FIFO_FULL_TEXT ("RAIL_EVENT_RX_FIFO_FULL")
#define RAIL_EVENT_RX_FIFO_OVERFLOW_TEXT ("RAIL_EVENT_RX_FIFO_OVERFLOW")
#define RAIL_EVENT_RX_ADDRESS_FILTERED_TEXT ("RAIL_EVENT_RX_ADDRESS_FILTERED")
#define RAIL_EVENT_RX_TIMEOUT_TEXT ("RAIL_EVENT_RX_TIMEOUT")
#define RAIL_EVENT_SCHEDULED_RX_STARTED_TEXT ("RAIL_EVENT_SCHEDULED_RX_STARTED")
#define RAIL_EVENT_SCHEDULED_TX_STARTED_TEXT ("RAIL_EVENT_SCHEDULED_TX_STARTED")
#define RAIL_EVENT_RX_SCHEDULED_RX_END_TEXT ("RAIL_EVENT_RX_SCHEDULED_RX_END")
#define RAIL_EVENT_RX_SCHEDULED_RX_MISSED_TEXT ("RAIL_EVENT_RX_SCHEDULED_RX_MISSED")
#define RAIL_EVENT_RX_PACKET_ABORTED_TEXT ("RAIL_EVENT_RX_PACKET_ABORTED")
#define RAIL_EVENT_RX_FILTER_PASSED_TEXT ("RAIL_EVENT_RX_FILTER_PASSED")
#define RAIL_EVENT_RX_TIMING_LOST_TEXT ("RAIL_EVENT_RX_TIMING_LOST")
#define RAIL_EVENT_RX_TIMING_DETECT_TEXT ("RAIL_EVENT_RX_TIMING_DETECT")
#define RAIL_EVENT_RX_CHANNEL_HOPPING_COMPLETE_TEXT ("RAIL_EVENT_RX_CHANNEL_HOPPING_COMPLETE")
#define RAIL_EVENT_RX_DUTY_CYCLE_RX_END_TEXT ("RAIL_EVENT_RX_DUTY_CYCLE_RX_END")
#define RAIL_EVENT_IEEE802154_DATA_REQUEST_COMMAND_TEXT ("RAIL_EVENT_IEEE802154_DATA_REQUEST_COMMAND")
#define RAIL_EVENT_MFM_TX_BUFFER_DONE_TEXT ("RAIL_EVENT_MFM_TX_BUFFER_DONE")
#define RAIL_EVENT_ZWAVE_LR_ACK_REQUEST_COMMAND_TEXT ("RAIL_EVENT_ZWAVE_LR_ACK_REQUEST_COMMAND")
#define RAIL_EVENTS_RX_COMPLETION_TEXT ("RAIL_EVENTS_RX_COMPLETION")
#define RAIL_EVENT_TX_FIFO_ALMOST_EMPTY_TEXT ("RAIL_EVENT_TX_FIFO_ALMOST_EMPTY")
#define RAIL_EVENT_TX_PACKET_SENT_TEXT ("RAIL_EVENT_TX_PACKET_SENT")
#define RAIL_EVENT_TXACK_PACKET_SENT_TEXT ("RAIL_EVENT_TXACK_PACKET_SENT")
#define RAIL_EVENT_TX_ABORTED_TEXT ("RAIL_EVENT_TX_ABORTED")
#define RAIL_EVENT_TXACK_ABORTED_TEXT ("RAIL_EVENT_TXACK_ABORTED")
#define RAIL_EVENT_TX_BLOCKED_TEXT ("RAIL_EVENT_TX_BLOCKED")
#define RAIL_EVENT_TXACK_BLOCKED_TEXT ("RAIL_EVENT_TXACK_BLOCKED")
#define RAIL_EVENT_TX_UNDERFLOW_TEXT ("RAIL_EVENT_TX_UNDERFLOW")
#define RAIL_EVENT_TXACK_UNDERFLOW_TEXT ("RAIL_EVENT_TXACK_UNDERFLOW")
#define RAIL_EVENT_TX_CHANNEL_CLEAR_TEXT ("RAIL_EVENT_TX_CHANNEL_CLEAR")
#define RAIL_EVENT_TX_CHANNEL_BUSY_TEXT ("RAIL_EVENT_TX_CHANNEL_BUSY")
#define RAIL_EVENT_TX_CCA_RETRY_TEXT ("RAIL_EVENT_TX_CCA_RETRY")
#define RAIL_EVENT_TX_START_CCA_TEXT ("RAIL_EVENT_TX_START_CCA")
#define RAIL_EVENT_TX_STARTED_TEXT ("RAIL_EVENT_TX_STARTED")
#define RAIL_EVENT_TX_SCHEDULED_TX_MISSED_TEXT ("1ULL << RAIL_EVENT_TX_SCHEDULED_TX_MISSED_SHIFT")
#define RAIL_EVENT_CONFIG_UNSCHEDULED_TEXT ("RAIL_EVENT_CONFIG_UNSCHEDULED")
#define RAIL_EVENT_CONFIG_SCHEDULED_TEXT ("RAIL_EVENT_CONFIG_SCHEDULED")
#define RAIL_EVENT_SCHEDULER_STATUS_TEXT ("RAIL_EVENT_SCHEDULER_STATUS")
#define RAIL_EVENT_CAL_NEEDED_TEXT ("RAIL_EVENT_CAL_NEEDED")
#define RAIL_EVENT_RF_SENSED_TEXT ("RAIL_EVENT_RF_SENSED")
#define RAIL_EVENT_PA_PROTECTION_TEXT ("RAIL_EVENT_PA_PROTECTION")
#define RAIL_EVENT_SIGNAL_DETECTED_TEXT ("RAIL_EVENT_SIGNAL_DETECTED")
#define RAIL_EVENT_IEEE802154_MODESWITCH_START_TEXT ("RAIL_EVENT_IEEE802154_MODESWITCH_START")
#define RAIL_EVENT_IEEE802154_MODESWITCH_END_TEXT ("RAIL_EVENT_IEEE802154_MODESWITCH_END")
#define RAIL_EVENT_DETECT_RSSI_THRESHOLD_TEXT ("RAIL_EVENT_DETECT_RSSI_THRESHOLD")
#define RAIL_EVENT_THERMISTOR_DONE_TEXT ("RAIL_EVENT_THERMISTOR_DONE")
#define RAIL_EVENT_TX_BLOCKED_TOO_HOT_TEXT ("RAIL_EVENT_TX_BLOCKED_TOO_HOT")
#define RAIL_EVENT_TEMPERATURE_TOO_HOT_TEXT ("RAIL_EVENT_TEMPERATURE_TOO_HOT")
#define RAIL_EVENT_TEMPERATURE_COOL_DOWN_TEXT ("RAIL_EVENT_TEMPERATURE_COOL_DOWN")


/*
RAIL_EVENT_RSSI_AVERAGE_DONE_TEXT
RAIL_EVENT_RX_ACK_TIMEOUT_TEXT
RAIL_EVENT_RX_FIFO_ALMOST_FULL_TEXT
RAIL_EVENT_RX_PACKET_RECEIVED_TEXT
RAIL_EVENT_RX_PREAMBLE_LOST_TEXT
RAIL_EVENT_RX_PREAMBLE_DETECT_TEXT
RAIL_EVENT_RX_SYNC1_DETECT_TEXT
RAIL_EVENT_RX_SYNC2_DETECT_TEXT
RAIL_EVENT_RX_FRAME_ERROR_TEXT
RAIL_EVENT_RX_FIFO_FULL_TEXT
RAIL_EVENT_RX_FIFO_OVERFLOW_TEXT
RAIL_EVENT_RX_ADDRESS_FILTERED_TEXT
RAIL_EVENT_RX_TIMEOUT_TEXT
RAIL_EVENT_SCHEDULED_RX_STARTED_TEXT
RAIL_EVENT_SCHEDULED_TX_STARTED_TEXT
RAIL_EVENT_RX_SCHEDULED_RX_END_TEXT
RAIL_EVENT_RX_SCHEDULED_RX_MISSED_TEXT
RAIL_EVENT_RX_PACKET_ABORTED_TEXT
RAIL_EVENT_RX_FILTER_PASSED_TEXT
RAIL_EVENT_RX_TIMING_LOST_TEXT
RAIL_EVENT_RX_TIMING_DETECT_TEXT
RAIL_EVENT_RX_CHANNEL_HOPPING_COMPLETE_TEXT
RAIL_EVENT_RX_DUTY_CYCLE_RX_END_TEXT
RAIL_EVENT_IEEE802154_DATA_REQUEST_COMMAND_TEXT
RAIL_EVENT_MFM_TX_BUFFER_DONE_TEXT
RAIL_EVENT_ZWAVE_LR_ACK_REQUEST_COMMAND_TEXT
RAIL_EVENTS_RX_COMPLETION_TEXT
RAIL_EVENT_TX_FIFO_ALMOST_EMPTY_TEXT
RAIL_EVENT_TX_PACKET_SENT_TEXT
RAIL_EVENT_TXACK_PACKET_SENT_TEXT
RAIL_EVENT_TX_ABORTED_TEXT
RAIL_EVENT_TXACK_ABORTED_TEXT
RAIL_EVENT_TX_BLOCKED_TEXT
RAIL_EVENT_TXACK_BLOCKED_TEXT
RAIL_EVENT_TX_UNDERFLOW_TEXT
RAIL_EVENT_TXACK_UNDERFLOW_TEXT
RAIL_EVENT_TX_CHANNEL_CLEAR_TEXT
RAIL_EVENT_TX_CHANNEL_BUSY_TEXT
RAIL_EVENT_TX_CCA_RETRY_TEXT
RAIL_EVENT_TX_START_CCA_TEXT
RAIL_EVENT_TX_STARTED_TEXT
RAIL_EVENT_TX_SCHEDULED_TX_MISSED_TEXT
RAIL_EVENT_CONFIG_UNSCHEDULED_TEXT
RAIL_EVENT_CONFIG_SCHEDULED_TEXT
RAIL_EVENT_SCHEDULER_STATUS_TEXT
RAIL_EVENT_CAL_NEEDED_TEXT
RAIL_EVENT_RF_SENSED_TEXT
RAIL_EVENT_PA_PROTECTION_TEXT
RAIL_EVENT_SIGNAL_DETECTED_TEXT
RAIL_EVENT_IEEE802154_MODESWITCH_START_TEXT
RAIL_EVENT_IEEE802154_MODESWITCH_END_TEXT
RAIL_EVENT_DETECT_RSSI_THRESHOLD_TEXT
RAIL_EVENT_THERMISTOR_DONE_TEXT
RAIL_EVENT_TX_BLOCKED_TOO_HOT_TEXT
RAIL_EVENT_TEMPERATURE_TOO_HOT_TEXT
RAIL_EVENT_TEMPERATURE_COOL_DOWN_TEXT



RAIL_EVENT_RSSI_AVERAGE_DONE
RAIL_EVENT_RX_ACK_TIMEOUT
RAIL_EVENT_RX_FIFO_ALMOST_FULL
RAIL_EVENT_RX_PACKET_RECEIVED
RAIL_EVENT_RX_PREAMBLE_LOST
RAIL_EVENT_RX_PREAMBLE_DETECT
RAIL_EVENT_RX_SYNC1_DETECT
RAIL_EVENT_RX_SYNC2_DETECT
RAIL_EVENT_RX_FRAME_ERROR
RAIL_EVENT_RX_FIFO_FULL
RAIL_EVENT_RX_FIFO_OVERFLOW
RAIL_EVENT_RX_ADDRESS_FILTERED
RAIL_EVENT_RX_TIMEOUT
RAIL_EVENT_SCHEDULED_RX_STARTED
RAIL_EVENT_SCHEDULED_TX_STARTED
RAIL_EVENT_RX_SCHEDULED_RX_END
RAIL_EVENT_RX_SCHEDULED_RX_MISSED
RAIL_EVENT_RX_PACKET_ABORTED
RAIL_EVENT_RX_FILTER_PASSED
RAIL_EVENT_RX_TIMING_LOST
RAIL_EVENT_RX_TIMING_DETECT
RAIL_EVENT_RX_CHANNEL_HOPPING_COMPLETE
RAIL_EVENT_RX_DUTY_CYCLE_RX_END
RAIL_EVENT_IEEE802154_DATA_REQUEST_COMMAND
RAIL_EVENT_MFM_TX_BUFFER_DONE
RAIL_EVENT_ZWAVE_LR_ACK_REQUEST_COMMAND
RAIL_EVENTS_RX_COMPLETION
RAIL_EVENT_TX_FIFO_ALMOST_EMPTY
RAIL_EVENT_TX_PACKET_SENT
RAIL_EVENT_TXACK_PACKET_SENT
RAIL_EVENT_TX_ABORTED
RAIL_EVENT_TXACK_ABORTED
RAIL_EVENT_TX_BLOCKED
RAIL_EVENT_TXACK_BLOCKED
RAIL_EVENT_TX_UNDERFLOW
RAIL_EVENT_TXACK_UNDERFLOW
RAIL_EVENT_TX_CHANNEL_CLEAR
RAIL_EVENT_TX_CHANNEL_BUSY
RAIL_EVENT_TX_CCA_RETRY
RAIL_EVENT_TX_START_CCA
RAIL_EVENT_TX_STARTED
RAIL_EVENT_TX_SCHEDULED_TX_MISSED
RAIL_EVENT_CONFIG_UNSCHEDULED
RAIL_EVENT_CONFIG_SCHEDULED
RAIL_EVENT_SCHEDULER_STATUS
RAIL_EVENT_CAL_NEEDED
RAIL_EVENT_RF_SENSED
RAIL_EVENT_PA_PROTECTION
RAIL_EVENT_SIGNAL_DETECTED
RAIL_EVENT_IEEE802154_MODESWITCH_START
RAIL_EVENT_IEEE802154_MODESWITCH_END
RAIL_EVENT_DETECT_RSSI_THRESHOLD
RAIL_EVENT_THERMISTOR_DONE
RAIL_EVENT_TX_BLOCKED_TOO_HOT
RAIL_EVENT_TEMPERATURE_TOO_HOT
RAIL_EVENT_TEMPERATURE_COOL_DOWN
 */


/*
#define RAIL_EVENTS_NONE 0ULL
#define RAIL_EVENT_RSSI_AVERAGE_DONE (1ULL << RAIL_EVENT_RSSI_AVERAGE_DONE_SHIFT)
#define RAIL_EVENT_RX_ACK_TIMEOUT (1ULL << RAIL_EVENT_RX_ACK_TIMEOUT_SHIFT)
#define RAIL_EVENT_RX_FIFO_ALMOST_FULL (1ULL << RAIL_EVENT_RX_FIFO_ALMOST_FULL_SHIFT)
#define RAIL_EVENT_RX_PACKET_RECEIVED (1ULL << RAIL_EVENT_RX_PACKET_RECEIVED_SHIFT)
#define RAIL_EVENT_RX_PREAMBLE_LOST (1ULL << RAIL_EVENT_RX_PREAMBLE_LOST_SHIFT)
#define RAIL_EVENT_RX_PREAMBLE_DETECT (1ULL << RAIL_EVENT_RX_PREAMBLE_DETECT_SHIFT)
#define RAIL_EVENT_RX_SYNC1_DETECT (1ULL << RAIL_EVENT_RX_SYNC1_DETECT_SHIFT)
#define RAIL_EVENT_RX_SYNC2_DETECT (1ULL << RAIL_EVENT_RX_SYNC2_DETECT_SHIFT)
#define RAIL_EVENT_RX_FRAME_ERROR (1ULL << RAIL_EVENT_RX_FRAME_ERROR_SHIFT)
#define RAIL_EVENT_RX_FIFO_FULL (1ULL << RAIL_EVENT_RX_FIFO_FULL_SHIFT)
#define RAIL_EVENT_RX_FIFO_OVERFLOW (1ULL << RAIL_EVENT_RX_FIFO_OVERFLOW_SHIFT)
#define RAIL_EVENT_RX_ADDRESS_FILTERED (1ULL << RAIL_EVENT_RX_ADDRESS_FILTERED_SHIFT)
#define RAIL_EVENT_RX_TIMEOUT (1ULL << RAIL_EVENT_RX_TIMEOUT_SHIFT)
#define RAIL_EVENT_SCHEDULED_RX_STARTED (1ULL << RAIL_EVENT_SCHEDULED_RX_STARTED_SHIFT)
#define RAIL_EVENT_SCHEDULED_TX_STARTED (1ULL << RAIL_EVENT_SCHEDULED_TX_STARTED_SHIFT)
#define RAIL_EVENT_RX_SCHEDULED_RX_END (1ULL << RAIL_EVENT_RX_SCHEDULED_RX_END_SHIFT)
#define RAIL_EVENT_RX_SCHEDULED_RX_MISSED (1ULL << RAIL_EVENT_RX_SCHEDULED_RX_MISSED_SHIFT)
#define RAIL_EVENT_RX_PACKET_ABORTED (1ULL << RAIL_EVENT_RX_PACKET_ABORTED_SHIFT)
#define RAIL_EVENT_RX_FILTER_PASSED (1ULL << RAIL_EVENT_RX_FILTER_PASSED_SHIFT)
#define RAIL_EVENT_RX_TIMING_LOST (1ULL << RAIL_EVENT_RX_TIMING_LOST_SHIFT)
#define RAIL_EVENT_RX_TIMING_DETECT (1ULL << RAIL_EVENT_RX_TIMING_DETECT_SHIFT)
#define RAIL_EVENT_RX_CHANNEL_HOPPING_COMPLETE (1ULL << RAIL_EVENT_RX_CHANNEL_HOPPING_COMPLETE_SHIFT)
#define RAIL_EVENT_RX_DUTY_CYCLE_RX_END (1ULL << RAIL_EVENT_RX_DUTY_CYCLE_RX_END_SHIFT)
#define RAIL_EVENT_IEEE802154_DATA_REQUEST_COMMAND (1ULL << RAIL_EVENT_IEEE802154_DATA_REQUEST_COMMAND_SHIFT)
#define RAIL_EVENT_MFM_TX_BUFFER_DONE (1ULL << RAIL_EVENT_MFM_TX_BUFFER_DONE_SHIFT)
#define RAIL_EVENT_ZWAVE_LR_ACK_REQUEST_COMMAND (1ULL << RAIL_EVENT_ZWAVE_LR_ACK_REQUEST_COMMAND_SHIFT)
#define RAIL_EVENTS_RX_COMPLETION (RAIL_EVENT_RX_PACKET_RECEIVED    \
                                   | RAIL_EVENT_RX_PACKET_ABORTED   \
                                   | RAIL_EVENT_RX_FRAME_ERROR      \
                                   | RAIL_EVENT_RX_FIFO_OVERFLOW    \
                                   | RAIL_EVENT_RX_ADDRESS_FILTERED \
                                   | RAIL_EVENT_RX_SCHEDULED_RX_MISSED)
#define RAIL_EVENT_TX_FIFO_ALMOST_EMPTY (1ULL << RAIL_EVENT_TX_FIFO_ALMOST_EMPTY_SHIFT)
#define RAIL_EVENT_TX_PACKET_SENT (1ULL << RAIL_EVENT_TX_PACKET_SENT_SHIFT)
#define RAIL_EVENT_TXACK_PACKET_SENT (1ULL << RAIL_EVENT_TXACK_PACKET_SENT_SHIFT)
#define RAIL_EVENT_TX_ABORTED (1ULL << RAIL_EVENT_TX_ABORTED_SHIFT)
#define RAIL_EVENT_TXACK_ABORTED (1ULL << RAIL_EVENT_TXACK_ABORTED_SHIFT)
#define RAIL_EVENT_TX_BLOCKED (1ULL << RAIL_EVENT_TX_BLOCKED_SHIFT)
#define RAIL_EVENT_TXACK_BLOCKED (1ULL << RAIL_EVENT_TXACK_BLOCKED_SHIFT)
#define RAIL_EVENT_TX_UNDERFLOW (1ULL << RAIL_EVENT_TX_UNDERFLOW_SHIFT)
#define RAIL_EVENT_TXACK_UNDERFLOW (1ULL << RAIL_EVENT_TXACK_UNDERFLOW_SHIFT)
#define RAIL_EVENT_TX_CHANNEL_CLEAR (1ULL << RAIL_EVENT_TX_CHANNEL_CLEAR_SHIFT)
#define RAIL_EVENT_TX_CHANNEL_BUSY (1ULL << RAIL_EVENT_TX_CHANNEL_BUSY_SHIFT)
#define RAIL_EVENT_TX_CCA_RETRY (1ULL << RAIL_EVENT_TX_CCA_RETRY_SHIFT)
#define RAIL_EVENT_TX_START_CCA (1ULL << RAIL_EVENT_TX_START_CCA_SHIFT)
#define RAIL_EVENT_TX_STARTED (1ULL << RAIL_EVENT_TX_STARTED_SHIFT)
#define RAIL_TX_STARTED_BYTES 0U
#define RAIL_EVENT_TX_SCHEDULED_TX_MISSED (1ULL << RAIL_EVENT_TX_SCHEDULED_TX_MISSED_SHIFT)
#define RAIL_EVENTS_TX_COMPLETION (RAIL_EVENT_TX_PACKET_SENT    \
                                   | RAIL_EVENT_TX_ABORTED      \
                                   | RAIL_EVENT_TX_BLOCKED      \
                                   | RAIL_EVENT_TX_UNDERFLOW    \
                                   | RAIL_EVENT_TX_CHANNEL_BUSY \
                                   | RAIL_EVENT_TX_SCHEDULED_TX_MISSED)
#define RAIL_EVENTS_TXACK_COMPLETION (RAIL_EVENT_TXACK_PACKET_SENT \
                                      | RAIL_EVENT_TXACK_ABORTED   \
                                      | RAIL_EVENT_TXACK_BLOCKED   \
                                      | RAIL_EVENT_TXACK_UNDERFLOW)
#define RAIL_EVENT_CONFIG_UNSCHEDULED (1ULL << RAIL_EVENT_CONFIG_UNSCHEDULED_SHIFT)
#define RAIL_EVENT_CONFIG_SCHEDULED (1ULL << RAIL_EVENT_CONFIG_SCHEDULED_SHIFT)
#define RAIL_EVENT_SCHEDULER_STATUS (1ULL << RAIL_EVENT_SCHEDULER_STATUS_SHIFT)
#define RAIL_EVENT_CAL_NEEDED (1ULL << RAIL_EVENT_CAL_NEEDED_SHIFT)
#define RAIL_EVENT_RF_SENSED (1ULL << RAIL_EVENT_RF_SENSED_SHIFT)
#define RAIL_EVENT_PA_PROTECTION (1ULL << RAIL_EVENT_PA_PROTECTION_SHIFT)
#define RAIL_EVENT_SIGNAL_DETECTED (1ULL << RAIL_EVENT_SIGNAL_DETECTED_SHIFT)
#define RAIL_EVENT_IEEE802154_MODESWITCH_START (1ULL << RAIL_EVENT_IEEE802154_MODESWITCH_START_SHIFT)
#define RAIL_EVENT_IEEE802154_MODESWITCH_END (1ULL << RAIL_EVENT_IEEE802154_MODESWITCH_END_SHIFT)
#define RAIL_EVENT_DETECT_RSSI_THRESHOLD (1ULL << RAIL_EVENT_DETECT_RSSI_THRESHOLD_SHIFT)
#define RAIL_EVENT_THERMISTOR_DONE (1ULL << RAIL_EVENT_THERMISTOR_DONE_SHIFT)
#define RAIL_EVENT_TX_BLOCKED_TOO_HOT (1ULL << RAIL_EVENT_TX_BLOCKED_TOO_HOT_SHIFT)
#define RAIL_EVENT_TEMPERATURE_TOO_HOT (1ULL << RAIL_EVENT_TEMPERATURE_TOO_HOT_SHIFT)
#define RAIL_EVENT_TEMPERATURE_COOL_DOWN (1ULL << RAIL_EVENT_TEMPERATURE_COOL_DOWN_SHIFT)
#define RAIL_EVENTS_ALL 0xFFFFFFFFFFFFFFFFULL
*/
#endif /* EVENTS_PRINTS_H_ */
